apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 10.0.66.200-10.0.66.252
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipv6-default
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 2001:4645:41da:66::f0-2001:4645:41da:66::ff
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ipAddressPools:
    - default
    - ipv6-default
#  interfaces:
#    - eth0   # replace with your host interface connected to pfSense
